<?php
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

function friday_api_page_attachments(array &$attachments) {
$attachments['#attached']['library'][] = 'friday_api/friday_api_js';

}

/**
 * Implements hook_theme() to add the template definition.
 **/
function friday_api_theme($existing, $type, $theme, $path) {
    return [
        'friday_api' => [
            'variables' => ['blogs' => NULL],
        ],
        'single_blog' => [
            'variables' => ['blogs' => NULL],
        ],
        'filter_api' => [
            'variables' => ['blogs' => NULL],
        ],

        'api-form-block' => [
            'variables' => [
                'blogs' => NULL,
                'form' => NULL
            ],
        ],
   
    ];
}


?>